
FILE_MODEL: xgb_model.pkl
FILE_SCALER: model_scaler.pkl

PATH_DATASET: ../_data_/data_churn_in_game/dataset/
PATH_MODEL: ../_data_/data_churn_in_game/model/
PATH_RAW_DATA: ../_data_/data_churn_in_game/
PATH_RAW_TEST: ../_data_/data_churn_in_game/test/
PATH_RAW_TRAIN: ../_data_/data_churn_in_game/train/

datasets:
  train:
    path: ../_data_/data_churn_in_game/dataset/
    file_raw: dataset_raw_train.csv
    file_model: dataset_train.csv
  test:
    path: ../_data_/data_churn_in_game/dataset/
    file_raw: dataset_raw_test.csv
    file_model: dataset_test.csv
  predict:
    path: ../_data_/data_churn_in_game/result/
    file_predict: prediction_result.csv
  sep: ;

model_threshold: 0.5

CHURNED_END_DATE: '2019-10-01'
CHURNED_START_DATE: '2019-09-01'

INTERLIST:
  - [1, 7]
  - [ 8, 14]
  - [15, 21]
  - [22, 28]
